/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BillboardScript")]
    [LuaRegisterType(0x4a1809a4d4d6f8bf, typeof(LuaBehaviour))]
    public class BillboardScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "801faa955c697e744bdb16d7a38463a4";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_locUp = false;
        [SerializeField] public UnityEngine.GameObject m_mainCam = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_locUp),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_mainCam),
            };
        }
    }
}

#endif
