/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DailyMetaData")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class DailyMetaData : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6d1b1b4adde11a047957d9e19cb37364";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_coinIcons = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_baitIcons = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_coinIcons),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_baitIcons),
            };
        }
    }
}

#endif
