/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FishingCharacterController")]
    [LuaRegisterType(0x6c1dd0ddd4bf1de8, typeof(LuaBehaviour))]
    public class FishingCharacterController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "07e01075e92b19d4b91edfeac4c0bcb5";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_movementIndicator = default;
        [SerializeField] public UnityEngine.GameObject m_fishingIndicator = default;
        [SerializeField] public Highrise.AudioShader m_longPressSound = default;
        [SerializeField] public Highrise.AudioShader m_footstepWalkSound = default;
        [SerializeField] public Highrise.AudioShader m_footstepRunSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_movementIndicator),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_fishingIndicator),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_longPressSound),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_footstepWalkSound),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_footstepRunSound),
            };
        }
    }
}

#endif
