/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FishingLine")]
    [LuaRegisterType(0x9a529a643c693377, typeof(LuaBehaviour))]
    public class FishingLine : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "440d5291b37d1644d8836e6ec2faad07";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Transform m_startPoint = default;
        [SerializeField] public UnityEngine.Transform m_endPoint = default;
        [SerializeField] public System.Double m_resolution = 20;
        [SerializeField] public System.Double m_curveHeight = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_startPoint),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_endPoint),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_resolution),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_curveHeight),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/FishingLine/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
