/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GeneralChatOverride")]
    [LuaRegisterType(0xaf4fc9d8f84b428d, typeof(LuaBehaviour))]
    public class GeneralChatOverride : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e0e374428bc6eff48a923f4fc564c9fa";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_maxVolumeDistance = 15;
        [SerializeField] public System.Double m_minVolumeDistance = 30;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_maxVolumeDistance),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_minVolumeDistance),
            };
        }
    }
}

#endif
