/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/IslandManager")]
    [LuaRegisterType(0x4fd5776329e1a673, typeof(LuaBehaviour))]
    public class IslandManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "0fc5ba8f14134274584baa07f7ae40b2";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_IslandPoints = default;
        [SerializeField] public System.Collections.Generic.List<System.Double> m_IslandLevelReqs = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_IslandPoints),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_IslandLevelReqs),
            };
        }
    }
}

#endif
