/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ItemMetaData")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class ItemMetaData : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b8cb0768fc7eb8847896188ad5a1f592";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_poleIcons = default;
        [SerializeField] public System.Collections.Generic.List<Highrise.CharacterOutfit> m_poleOutfits = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_baitIcons = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_dealsIcons = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_poleIcons),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_poleOutfits),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_baitIcons),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_dealsIcons),
            };
        }
    }
}

#endif
