/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/MissionsModule")]
    [LuaRegisterType(0x81693233cb2c975a, typeof(LuaBehaviour))]
    public class MissionsModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "0515ab83287854b7289f617ded0276df";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_env = "dev";
        [SerializeField] public System.String m_worldId = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_env),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_worldId),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/MissionsModule/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
