/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/MoveTowardPlayer")]
    [LuaRegisterType(0x87771004704bd29a, typeof(LuaBehaviour))]
    public class MoveTowardPlayer : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "23b2ac6b851124842804dccff72b5212";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_speed = 1;
        [SerializeField] public System.Double m_range = 5;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_speed),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_range),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/MoveTowardPlayer/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
