/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SimpleBillboard")]
    [LuaRegisterType(0x63b985b4edb38e1a, typeof(LuaBehaviour))]
    public class SimpleBillboard : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3ceab48c95daa604688c3d970e7a2720";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_billboard = true;
        [SerializeField] public UnityEngine.Vector3 m_amount = new Vector3(1f, 1f, 1f);
        [SerializeField] public UnityEngine.Vector3 m_offset = new Vector3(0f, 0f, 0f);
        [SerializeField] public UnityEngine.Camera m_cameraOverride = default;
        [SerializeField] public System.Boolean m_useInitialRotation = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_billboard),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_amount),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_offset),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_cameraOverride),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_useInitialRotation),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/SimpleBillboard/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
