/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManager")]
    [LuaRegisterType(0x4420fd164eed93fa, typeof(LuaBehaviour))]
    public class UIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "976710b7145604d479b1557d77053249";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_InventoryObject = default;
        [SerializeField] public UnityEngine.GameObject m_LeaderboardObject = default;
        [SerializeField] public UnityEngine.GameObject m_ShopObject = default;
        [SerializeField] public UnityEngine.GameObject m_WorldHudObject = default;
        [SerializeField] public UnityEngine.GameObject m_FishingHudObject = default;
        [SerializeField] public UnityEngine.GameObject m_ItemPopupObject = default;
        [SerializeField] public UnityEngine.GameObject m_RewardPopupObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_InventoryObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_LeaderboardObject),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_ShopObject),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_WorldHudObject),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_FishingHudObject),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_ItemPopupObject),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_RewardPopupObject),
            };
        }
    }
}

#endif
