/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIModule")]
    [LuaRegisterType(0xe8e6e3a8703514f7, typeof(LuaBehaviour))]
    public class UIModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fbc293dee06d78f45a93eba1ff5aa680";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_EventHudOBJ = default;
        [SerializeField] public UnityEngine.GameObject m_energyRefillPopup = default;
        [SerializeField] public UnityEngine.GameObject m_superBoostPopup = default;
        [SerializeField] public UnityEngine.GameObject m_energyWidget = default;
        [SerializeField] public UnityEngine.GameObject m_EventOverUI = default;
        [SerializeField] public UnityEngine.GameObject m_ticketsIndicator = default;
        [SerializeField] public UnityEngine.GameObject m_EventObjs = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_EventHudOBJ),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_energyRefillPopup),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_superBoostPopup),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_energyWidget),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_EventOverUI),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_ticketsIndicator),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_EventObjs),
            };
        }
    }
}

#endif
