/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/WaterType")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class WaterType : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "dfee82da9d8c2d34a8bd872e26f9239e";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_waterBiome = "any";
        [SerializeField] public System.String m_lockedAlert = "any";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_waterBiome),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_lockedAlert),
            };
        }
    }
}

#endif
